apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-broker
  labels:
    app: {{ .Values.name }}
    component: broker
{{- if .Values.deployment.broker.labels }}
{{ toYaml .Values.deployment.broker.labels | indent 4 }}
{{- end }}
{{- if .Values.deployment.broker.annotations }}
  annotations:
{{ toYaml .Values.deployment.broker.annotations | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicas.broker }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
      component: broker
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: broker
    spec:
      containers:
      - name: {{ .Values.name }}-broker
        image: {{ .Values.images.broker.repository }}:{{ .Values.images.broker.tag }}
        imagePullPolicy: {{ .Values.images.broker.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.broker.targetPort }}
          protocol: TCP
        resources:
{{ toYaml .Values.resources.broker | indent 10 }}
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: {{ .Values.service.broker.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: {{ .Values.service.broker.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: BROKER_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.broker.secretName }}
              key: {{ .Values.broker.secretKey }}
        - name: CR_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cr.secretName }}
              key: {{ .Values.cr.secretKey }}
        - name: CR_AGENT_URL
          value: {{ .Values.cr.url }}
        - name: BROKER_CLIENT_URL
          value: {{ .Values.broker.url }}
        - name: PORT
          value: "{{ .Values.service.broker.targetPort }}"
{{- if .Values.ca }}
        - name: CA_CERT
          value: {{ .Values.ca }}
{{- end }}
