{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  name: {{ template "fullname" . }}
  labels:
    app: {{ .Values.name }}
{{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts.broker }}
  - host: {{ . }}
    http:
      paths:
      - backend:
          serviceName: {{ template "fullname" $ }}-broker
          servicePort: {{ .Values.service.broker.port }}
        path: /
  {{- end }}
  {{- range .Values.ingress.hosts.cr-agent }}
  - host: {{ . }}
    http:
      paths:
      - backend:
          serviceName: {{ template "fullname" $ }}-cr-agent
          servicePort: {{ .Values.service.cr-agent.port }}
        path: /
  {{- end }}  
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
{{- end -}}
