{{- if not .Values.cr.useExistingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cr.secretName }}
  labels:
    app: {{ .Values.name }}
type: Opaque
data:
  {{ .Values.cr.secretKey}}: {{ .Values.cr.credentials | b64enc | quote }}
{{- end -}}
