apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-cr-agent
  labels:
    app: {{ .Values.name }}
    component: cr-agent
{{- if .Values.service.cr-agent.labels }}
{{ toYaml .Values.service.cr-agent.labels | indent 4 }}
{{- end }}
{{- if .Values.service.cr-agent.annotations }}
  annotations:
{{ toYaml .Values.service.cr-agent.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.cr-agent.type }}
  ports:
  - port: {{ .Values.service.cr-agent.port }}
    protocol: TCP
    targetPort: {{ .Values.service.cr-agent.targetPort }}
{{ if (and (eq .Values.service.cr-agent.type "NodePort") (not (empty .Values.service.cr-agent.nodePort))) }}
    nodePort: {{ .Values.service.cr-agent.nodePort }}
{{ end }}
  selector:
    app: {{ .Values.name }}
    component: cr-agent
  sessionAffinity: None
